name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Ensure a clean installation
        run: npm ci
      - name: Compile, lint and test
        run: xvfb-run -a npm test
